version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tankmaintainer-backend
    restart: unless-stopped
    ports:
      - "8080:8080" # Expose Spring Boot on port 8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/tankmaintainer?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: tankuser
      SPRING_DATASOURCE_PASSWORD: strongpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
    networks:
      - tank_network

# Networks for isolated communication between containers
networks:
  tank_network:
    driver: bridge